name: Python package

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # pulls all commits and tags (needed by pbr)
        fetch-depth: "0"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-console-scripts
        python -m pip install -r requirements.txt .
    - name: Test with pytest
      run: |
        sudo python -m pytest -v
    - name: Build release distributions
      run: |
        python -m pip install build
        python -m build
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/


  test-pypi-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build

    environment:
      name: testpypi
      url: https://test.pypi.org/p/iproute4mac

    permissions:
      id-token: write

    steps:
    - name: Retrieve release distributions
      uses: actions/download-artifact@v4
      with:
        name: release-dists
        path: dist/

    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/


  pypi-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    - test-pypi-publish

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/iproute4mac

    steps:
    - name: Retrieve release distributions
      uses: actions/download-artifact@v4
      with:
        name: release-dists
        path: dist/

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}


  github-release:
    runs-on: ubuntu-latest
    needs:
    - pypi-publish

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Retrieve release distributions
      uses: actions/download-artifact@v4
      with:
        name: release-dists
        path: dist/

    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v2.1.1
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create '${{ github.ref_name }}' --repo '${{ github.repository }}' --generate-notes

    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release upload '${{ github.ref_name }}' dist/** --repo '${{ github.repository }}'


  update-homebrew-releases:
    runs-on: ubuntu-latest
    needs:
    - pypi-publish

    steps:
    - name: Update Homebrew releases
      run: |
        curl -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.UPDATE_RELEASES_TOKEN }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -d '{"event_type":"update-releases"}' \
             -fsSL "https://api.github.com/repos/signal-09/homebrew-tap/dispatches"
